export const buttons = {
  btn1: {
    style: {
      backgroundColor: '#007BFF',
      color: 'white',
      border: 'none',
      padding: '10px 20px',
      borderRadius: '5px',
      fontSize: '16px',
      cursor: 'pointer',
      transition: 'background-color 0.3s ease',
    },
    hover: {
      backgroundColor: '#0056b3',
      color: 'white',
      border: 'none',
      padding: '10px 20px',
      borderRadius: '5px',
      fontSize: '16px',
      cursor: 'pointer',
    },
  },
  btn2: {
    style: {
      backgroundColor: '#3e8e41',
      color: 'white',
      border: '2px solid #2c6e2f',
      padding: '12px 24px',
      borderRadius: '50px',
      fontSize: '18px',
      fontWeight: 'bold',
      cursor: 'pointer',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
      transition: 'transform 0.3s ease, background-color 0.3s ease',
    },
    hover: {
      backgroundColor: '#267a2f',
      transform: 'scale(1.05)',
      color: 'white',
      border: '2px solid #2c6e2f',
      padding: '12px 24px',
      borderRadius: '50px',
      fontSize: '18px',
      fontWeight: 'bold',
      cursor: 'pointer',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    },
  },
  
  btn3: {
    style: {
      backgroundColor: 'transparent',
      color: '#007BFF',
      border: '2px solid #007BFF',
      padding: '10px 20px',
      borderRadius: '30px',
      fontSize: '16px',
      cursor: 'pointer',
      transition: 'color 0.3s ease, background-color 0.3s ease',
    },
    hover: {
      color: 'white',
      backgroundColor: '#007BFF',
      border: '2px solid #007BFF',
      padding: '10px 20px',
      borderRadius: '30px',
      fontSize: '16px',
      cursor: 'pointer',
    },
  },
  
  btn4: {
    style: {
      backgroundColor: '#28a745',
      color: 'white',
      border: 'none',
      padding: '12px 30px',
      borderRadius: '50px',
      fontSize: '18px',
      fontWeight: 'bold',
      cursor: 'pointer',
      boxShadow: '0 6px 12px rgba(0, 0, 0, 0.1)',
      transition: 'box-shadow 0.3s ease, background-color 0.3s ease',
    },
    hover: {
      backgroundColor: '#218838',
      color: 'white',
      border: 'none',
      padding: '12px 30px',
      borderRadius: '50px',
      fontSize: '18px',
      fontWeight: 'bold',
      cursor: 'pointer',
      boxShadow: '0 8px 16px rgba(0, 0, 0, 0.2)',
    },
  },
};
